name: Pull Request Stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@0dde6edf8b7db75684533021212c6e85fb987dbb # master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          period: 30
          charts: true
          disable-links: true
          sort-by: 'COMMENTS'